steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "us-central1-docker.pkg.dev/notely-483004/notely-ar-repo/notely:$SHORT_SHA", "."]

  - name: gcr.io/cloud-builders/docker
    args:
      ["push", "us-central1-docker.pkg.dev/notely-483004/notely-ar-repo/notely:$SHORT_SHA"]

  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "run", "deploy", "notely",
        "--image", "us-central1-docker.pkg.dev/notely-483004/notely-ar-repo/notely:$SHORT_SHA",
        "--region", "us-central1",
        "--platform", "managed",
        "--allow-unauthenticated"
      ]

images:
  - us-central1-docker.pkg.dev/notely-483004/notely-ar-repo/notely:$SHORT_SHA
